### ISSUE TITLE
upper-case class names no longer recognized [experimental language server]

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/vscode-motoko#105]
<img width="1036" alt="Screenshot 2022-10-24 at 15 45 46" src="https://user-images.githubusercontent.com/32162112/197540754-43dd316f-4580-4c82-b073-c8d3dc96cbd3.png">

previously it didn't matter to the language server wether it was `../Ext/Common.mo` or `../ext/Common.mo`

Now if it's `Ext` instead of `ext` apparently the LS thinks that it's a Lib folder, not a single file.

**Comment by rvanasa** [comment]
Closing for now (let me know if you'd like me to re-open this issue).
