### ISSUE TITLE
Issues with vessel

### ISSUE THREAD

**Issue by cybrowl** [dfinity/vscode-motoko#120]
<img width="916" alt="Screen Shot 2022-12-08 at 1 47 15 PM" src="https://user-images.githubusercontent.com/93851200/206574402-7e4eec90-8eb4-4a13-b685-0fa18edc0291.png">

I will keep looking into this issue but `.vessel` is installed in the project. Not sure if there is something else I need to do for it to find those references. 

Thanks again for help.

**Comment by ggreif** [comment]
First question: if you open the terminal pane in VSC, what does
``` shell
which vessel
```
say?

**Comment by rvanasa** [comment]
There is now a fallback Vessel installation built into the extension, so you might be running into some unexpected corner case with this new feature. 

Would you mind sending any error messages which appear in the "Motoko Language Server" output panel? You should be able to find this between the "Problems" and "Terminal" tabs in your workspace.

**Comment by cybrowl** [comment]
> First question: if you open the terminal pane in VSC, what does
> 
> ```shell
> which vessel
> ```
> 
> say?

`/usr/local/bin/vessel`

**Comment by cybrowl** [comment]
> A fallback Vessel installation is now built into the extension, so you might be running into some unexpected corner case with this new feature.
> 
> Would you mind sending any error messages which appear in the "Motoko Language Server" output panel? You should be able to find this between the "Problems" and "Terminal" tabs in your workspace.
> 
> Also, what operating system are you using so I can try to reproduce this issue?
<img width="623" alt="Screen Shot 2022-12-09 at 12 23 32 AM" src="https://user-images.githubusercontent.com/93851200/206657676-35d2fae3-3ca0-4d60-83a0-081f32d6a754.png">
I don't see it. Is there a way to enable it?

**Comment by rvanasa** [comment]
This is where the logs are located (make sure to open a Motoko file to activate the extension):

<img width="1357" alt="Screenshot 2022-12-09 at 11 45 12 AM" src="https://user-images.githubusercontent.com/522097/206771717-5cdbfa27-4b28-46ff-b998-ed3c3609a249.png">

I just published `v0.6.1` which will provide some additional error output for this situation.

**Comment by cybrowl** [comment]
The new update fixed it. 

<img width="1075" alt="Screen Shot 2022-12-09 at 1 00 30 PM" src="https://user-images.githubusercontent.com/93851200/206795467-7c7a90f3-c21d-49a7-b0d8-d3616e322c43.png">
<img width="1022" alt="Screen Shot 2022-12-09 at 12 58 26 PM" src="https://user-images.githubusercontent.com/93851200/206795469-6875c120-5037-4dcf-8ae5-ed9d05911bf0.png">
<img width="1076" alt="Screen Shot 2022-12-09 at 12 58 15 PM" src="https://user-images.githubusercontent.com/93851200/206795472-b93b1fae-d954-4c42-82dc-2113d41dc32a.png">
 Here are some screenshots of the previous error and output from version 0.6.1

**Comment by rvanasa** [comment]
Thank you for the screenshots! This is enough information to fully understand the issue.
