### ISSUE TITLE
100% CPU load with this extension

### ISSUE THREAD

**Issue by ZenVoich** [dfinity/vscode-motoko#164]
When I'm working on mops VSCode loads the cpu at 100%.

Checked versions:
0.8.2 - 100% CPU load
0.7.4 - 100% CPU load
0.6.4 - works fine

**Comment by rvanasa** [comment]
Thanks for checking each of these extension versions. Does anything look out of place in the "Output" tab (after selecting "Motoko Language Server")? 

<img width="1361" alt="Screenshot 2023-02-02 at 11 49 49 AM" src="https://user-images.githubusercontent.com/522097/216421616-028611e3-d2d9-4450-8a88-2daedbfed33d.png">

**Comment by ZenVoich** [comment]
I see that it calls `mops sources` for each nested package that was created for testing)
![image](https://user-images.githubusercontent.com/21315978/216517336-fec7ec81-c7e7-4317-990f-b38f19e384d7.png)
and some of them (which didn't run `mops install`) get these errors:
![image](https://user-images.githubusercontent.com/21315978/216517781-a851a4ef-ac96-4372-85ea-2cbe09cf69bc.png)
All these commands are run every time when I open new motoko file or change motoko file, and loads CPU for 100% for ~13 seconds.

Some possible solutions that I see:
- In mops, I could remove all these 'testing packages' and replace them with script to generate packages and/or add e2e tests
- In mops, run `mops install` when `mops sources` is called
- In the extension, cache `mops sources` result based on `mops.toml` the md5 hash
- In the extension, cache the AST of the source files based on the md5 hash
- In the extension, add setting to exclude some paths

**Comment by rvanasa** [comment]
Gotcha. It looks like the extension is trying to automatically re-check for MOPS packages on file save, which was introduced as a way to fix various issues with users installing Vessel / MOPS without restarting the VS Code language server.

What's your opinion on running `mops install` upon calling `mops sources`? This is the default behavior for Vessel, so I originally built the integration around this assumption. 

I could also add a setting to deactivate this retry-on-save behavior so that you can add it to your `.vscode/settings.json` file for this workspace.

**Comment by ZenVoich** [comment]
> What's your opinion on running mops install upon calling mops sources? This is the default behavior for Vessel, so I originally built the integration around this assumption.

Added running `mops install` upon calling `mops sources` in mops cli 0.6.4

**Comment by rvanasa** [comment]
Great; thanks! Does this fix the issue, or would it be helpful for me to also include the retry-on-save setting?

**Comment by ZenVoich** [comment]
> Does this fix the issue

Unfortunately doesn't, but removing all my test packages helps, I will try to remove them in favor of generating packages for testing.

> would it be helpful for me to also include the retry-on-save setting?

not sure if this will help

**Comment by rvanasa** [comment]
Looking at the implementation, the extension ignores directories starting with a `.` (e.g. `test/.projects/...`). This appears to work as a temporary fix in my local `mops` repository. I'll also open a PR to include some additional caching for commands such as `mops sources`.

**Comment by rvanasa** [comment]
I found some additional ways to improve performance in #171 and #172; let me know if this ends up helping.

**Comment by ZenVoich** [comment]
I can see that it only uses CPU on startup, not every time a file is opened or modified.
Also I prefixed the test folders with `.` and that worked well too. Thank you

**Comment by rvanasa** [comment]
Glad to hear. Closing for now, and happy to reopen if needed.
