### ISSUE TITLE
operator is not the reserved keywords, but it is highlighted like keyword

### ISSUE THREAD

**Issue by flyq** [dfinity/vscode-motoko#19]
operator is not the [reserved keywords](https://sdk.dfinity.org/docs/developers-guide/basic-syntax-rules.html#_reserved_keywords), but it is highlighted like keyword:

![image](https://user-images.githubusercontent.com/16486808/133717784-5b9d8beb-ed78-4211-b29f-5d6b1e802b6c.png)

**Comment by rvanasa** [comment]
Fixed in the upcoming release. Cheers!
