### ISSUE TITLE
VSCode extension allows Trie.empty() with no generic type but moc throws error

### ISSUE THREAD

**Issue by jzxchiang1** [dfinity/vscode-motoko#21]
Let's say you have a record typed as such:
```
public type Foo = {
    var map: Trie.Trie<Text, Nat>;
};
```
And you initialize a record of type `Foo` as such:
```
let foo: Foo = {
    var map = Trie.empty();
};
```
The VSCode extension is totally fine with this and throws no error.

But when you run `dfx build`, the compiler complains with this:
```
Stderr:
Ill-typed intermediate code after Desugaring (use -v to see dumped IR):
(unknown location): IR type error [M0000], subtype violation:
  {var map : Trie<None, None>}
  {var map : Trie<Text, Nat>}
```
Note: this only happens if the field is prefixed with `var`.

**Comment by rvanasa** [comment]
Closing (feel free to create an issue on [dfinity/motoko](https://github.com/dfinity/motoko) if this is still relevant).
