### ISSUE TITLE
[Request] Please add option to disable context menu "Motoko: Deploy (20 Minutes)"

### ISSUE THREAD

**Issue by AVOlight** [dfinity/vscode-motoko#215]
Personally use "Go to Definition" which is usually at the top of the context menu
now "Motoko: Deploy (20 Minutes)" is 😅

**Comment by rvanasa** [comment]
Totally makes sense! I've changed the position to around the middle of the context menu in `v0.13.1`; let me know if this works better for you.

**Comment by AVOlight** [comment]
Yes, Thank You Very Much 😁
hopefully we also get a settings option for this and any thing added in future to the context menu
