### ISSUE TITLE
Can't find extension on vscode

### ISSUE THREAD

**Issue by Kariuki62** [dfinity/vscode-motoko#27]
I just can't find the Motoko extension on my vscode I also tried the contributing commands still I can't install. I also have both node and npm installed but still I'm unable to install the extension.

**Comment by rvanasa** [comment]
As an open-source contributor, here's how I package and install the extension:

- After cloning the repository, run `npm install` to download all the npm dependencies.
- Run `npm run package` to generate the `.vsix` file in the root directory of the repository.
- Right-click on the newly generated `vscode-motoko-0.3.9.vsix` (in the root directory) and select "Install Extension VSIX" (at the bottom of the menu).

Hopefully this helps! If you're running into a different issue and get a chance to send an error log, I'll do my best to point you in the right direction.

**Comment by rvanasa** [comment]
In case anyone finds this in the future, the VS Code extension is [available here](https://marketplace.visualstudio.com/items?itemName=dfinity-foundation.vscode-motoko).
