### ISSUE TITLE
Language service fails to start

### ISSUE THREAD

**Issue by opsbrown** [dfinity/vscode-motoko#28]
# Motoko:Start/Restart language service 
Motoko Extension v0.3.9
VSCode v1.67.2
Windows 10 Pro

## Issue
The service fails to start automatically or manually
Entry points tried: the '.mo' file, project directory, directory containing the .mo file

## Screenshots
Error from command palette
![Capture](https://user-images.githubusercontent.com/63460669/172261496-90b5d7fc-1afe-4a7c-a487-6ca6c8d3ab92.PNG)

Error after running service from command palette
![Capture](https://user-images.githubusercontent.com/63460669/172261847-be111fa8-f864-4f8f-a56e-78e0bc58878c.PNG)

Error in Output pane
![Capture](https://user-images.githubusercontent.com/63460669/172262131-91d85184-381f-4459-a122-eb47e7c86f1a.PNG)

**Comment by rvanasa** [comment]
This should be fixed in recent updates. Otherwise, definitely let me know and I'll reopen the issue.
