### ISSUE TITLE
Cannot find module '@napi-rs/lzma-linux-x64-gnu' in WSL

### ISSUE THREAD

**Issue by baolongt** [dfinity/vscode-motoko#283]
Hi, I do face an error from the packtool
```
[Warn  - 10:12:30 PM] Error: Error while running `defaults.build.packtool` in `dfx.json` config file:
Command failed: ic-mops sources
```

My dfx.json
```
  "build": {
      "packtool": "ic-mops sources",
      "args": ""
    },
```

I think it's problem from `mops` team but my `mops` cli faced this error and I fixed it but don't know why the extension still like this

**Comment by rvanasa** [comment]
Thanks for reaching out! It should be possible to fix this by changing the packtool command to either "npx ic-mops sources" or "mops sources" depending on how you installed the Mops CLI.

**Comment by baolongt** [comment]
oh it work <3 thanks
