### ISSUE TITLE
Feature Request: Data type on variable hover

### ISSUE THREAD

**Issue by Gekctek** [dfinity/vscode-motoko#287]
One feature that I have needed for a while is being able to see type/function information on hover in vscode.
Im not sure how to get the type of a variable without inferring or declaring a type for it and see if there is an error or its ok
Also a common issue I have is seeing method signature. If I break it it gives me an error message which I can figure it out or I just change the function name to something invalid, then look at the available functions in the module in the error message there

Would be nice to just quickly see basic information on variables/functions without having to look at error messages or F12 into the module

**Comment by rvanasa** [comment]
This should be available (along with doc comments for functions, modules, etc.) in the latest version of the extension:

<img width="254" alt="image" src="https://github.com/dfinity/vscode-motoko/assets/522097/77422b9c-c426-4d85-ae73-7d30b8d5346b">

<img width="339" alt="image" src="https://github.com/dfinity/vscode-motoko/assets/522097/8612e84f-834a-460d-83b2-fd32cd439451">

Does anything look unusual in the "Motoko Language Server" output logs?

<img width="1198" alt="image" src="https://github.com/dfinity/vscode-motoko/assets/522097/d5644115-01ee-4d53-8f46-a9155f9d085b">

**Comment by Gekctek** [comment]
You're right. I guess the issue is when there is ANY error in the file, which is the time when i care about what the type/signature is
I think this is a general issue with things not working/parsing correctly with errors, but I doubt its trivial issue

**Comment by rvanasa** [comment]
I see what you're saying; yes, this is a known limitation. I'll keep this in mind in case there's a way to improve this as part of the next batch of changes to the VS Code extension.
