### ISSUE TITLE
Publish v0.4.0 to Visual Studio Marketplace

### ISSUE THREAD

**Issue by rvanasa** [dfinity/vscode-motoko#37]
@kritzcreek, do you know who currently has access to the VS Marketplace publisher for this extension? 

I am hoping to start up the release pipeline again, which will involve getting access to the publisher account and creating a new access token. 

Thanks for your help!

CC @crusso @ggreif @krpeacock

**Comment by ggreif** [comment]
Wow, you did it! https://marketplace.visualstudio.com/items?itemName=dfinity-foundation.vscode-motoko

**Comment by rvanasa** [comment]
Good point! I found a way to retroactively upload 0.4.0 for completeness. 

After finishing up a few more LSP improvements based on [this forum conversation](https://forum.dfinity.org/t/motoko-language-server-not-finding-problems/15471/17), perhaps we could make a wider announcement about the updated extension.
