### ISSUE TITLE
DFX 0.11.2

### ISSUE THREAD

**Issue by maxm224** [dfinity/vscode-motoko#43]
After upgrading to dfx 0.11.2. The extension seems to start correctly.
![image](https://user-images.githubusercontent.com/111142700/190929512-80bb1add-bc2f-4541-aa7d-0a07af3a2771.png)
However no errors are being shown. When I downgrade back to 0.10.0 everything works fine again and errors are highlighted.

**Comment by rvanasa** [comment]
Errors and warnings should work again in the latest version of the extension (`v0.4.2`). 

`dfx` versions >= `0.11.1` now use a new cross-platform language server ([more details here](https://github.com/dfinity/vscode-motoko#recent-changes)). 

We are redesigning this extension based on feedback from the [Motoko Developer Experience Survey](https://forum.dfinity.org/t/announcing-the-motoko-developer-experience-survey/15235), so thank you for your patience during this transitional period between the two language server implementations.
