### ISSUE TITLE
motoko template files

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#51]
I have Go code that generates Motoko, and the vs code plugin is recognising the template files and giving me errors.  I renamed them to .mt not .mo and that worked before, but now the latest 0.4.4 is generating errors.

Could we please have a setting that allows us to specify the file extension?  I've seen that on a few things like prettify.  Or maybe there's a better solution.

![image](https://user-images.githubusercontent.com/84897664/191925799-0255ae2f-f8b0-4a1a-8aca-4510a6abd97c.png)

Thanks

**Comment by rvanasa** [comment]
Just to make sure I understand, are you hoping to keep the syntax highlighting on `*.mt` files without generating type errors? 

If you just want to skip checking these template files, I could look into adding the ability to ignore specific files using something like a `// @motoko-ignore-file` line comment. Would this work for your use case?

**Comment by borovan** [comment]
The highlighting is fine, but there doesn't need to be any errors at all.  That's how it was previously anyway.

The issue with the comment is that it then gets into the generated file, so I have to code around that.  I'm sure there's something in the go templating library that can get around that but it could be messy.

What about something like :

Highlighting:
File patterns to apply syntax text highlighting to:
Default : *.mo

Error Checking:
File patterns to check for compiler problems:
Default : *.mo

That may not be the best solution, but it would solve our problems.  Thanks!

**Comment by rvanasa** [comment]
For consistency between projects and editors, I added syntax highlighting for `*.mo_` files in `v0.4.6` of the extension. 

Let me know if this works for now, and I'll run this past the rest of the Motoko team to figure out how we want to support these sorts of use cases in general.

**Comment by borovan** [comment]
Yeah, that's fine... all implemented.  If it changes that's fine.

Thanks again!
