### ISSUE TITLE
do {} statement prettifies to one long line?

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#52]
I may have got this wrong, but here's the before and after...

![image](https://user-images.githubusercontent.com/84897664/192118391-8dcb51c1-9eb8-4365-8153-16f4bd044474.png)

![image](https://user-images.githubusercontent.com/84897664/192118401-c03a1514-ae26-453a-9099-ce674426e318.png)

it appears to be something to do with the initial (( as I'm passing a tuple into the Buffer.  If I change it to a single bracket the code doesn't work but the formatting looks normal.

![image](https://user-images.githubusercontent.com/84897664/192118467-e1915908-9944-4870-a667-a552875ade14.png)

**Comment by rvanasa** [comment]
Fixed in https://github.com/dfinity/prettier-plugin-motoko/pull/53 and should work as expected in the next version of the extension. Cheers!

**Comment by borovan** [comment]
awesome, thanks!  the more you fix the more I will bug you:)
