### ISSUE TITLE
files being checked for errors after deletion

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#60]
So we generate a bunch of files in a generated/ directory, and then move them to where they're supposed to live.  I think we're going to change this to write the files directly (which would fix this bug for us.)  Anyway,

![image](https://user-images.githubusercontent.com/84897664/193411059-a326dfe9-494c-405e-b9c5-f9c7e895c0ab.png)
![image](https://user-images.githubusercontent.com/84897664/193411062-fd35c831-20c8-487a-81a2-f060bdc766b6.png)

After the files are moved we still get all these phantom errors appearing.

**Comment by rvanasa** [comment]
Thanks for reporting all these subtle issues! Fixed in `v0.4.7`.
