### ISSUE TITLE
space after tuple variable

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#74]
![image](https://user-images.githubusercontent.com/84897664/195983106-a2393273-1ec1-43c8-8fa5-2bfb2aaa36b2.png)

Have to do this in two steps, because row.1.record changes to row.1. record.

Thanks again!

**Comment by rvanasa** [comment]
Fixed in `prettier-plugin-motoko 0.2.2` / `vscode-motoko 0.5.1`.
