### ISSUE TITLE
inconsistent spacing for query() and shared() in actor

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#75]
![image](https://user-images.githubusercontent.com/84897664/195983354-31b942f6-bfcb-4519-a792-54b47904de7c.png)

![image](https://user-images.githubusercontent.com/84897664/195983372-007c76db-9dad-4e68-aab1-97e99745cb23.png)

I'm using the latest prettier and vscode plugin... and when I save the file it removes the space between shared and ({ caller }).  Then when I run prettier it adds it back.

**Comment by rvanasa** [comment]
Updated the formatter which is bundled in the VS Code extension. Let me know if you still run into this issue. 

The extension might also be reading an outdated plugin version from `package.json` (the expected version is `0.2.2`).

**Comment by borovan** [comment]
Yup all good, thanks again!

**Comment by borovan** [comment]
![image](https://user-images.githubusercontent.com/84897664/196035572-7fa58037-dd22-47e4-8fb2-f26a18139a9f.png)

This is the only difference between our code generators and the prettified format, just checking that's ok.

**Comment by borovan** [comment]
Sorry, it may seem like I have extreme OCD about this, but that's because I literally do.
