### ISSUE TITLE
Import error at top line of each file when writing a module

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/vscode-motoko#90]
When developing a module, I often find that the top line of the file has the following error, regardless of if that line contains an import or not.

![Screen Shot 2022-11-02 at 20 42 50](https://user-images.githubusercontent.com/17368530/199644068-e514dc8e-c70b-4f6e-a557-ea49b8955a82.png)

Hovering over red underline shows the following error:

![Screen Shot 2022-11-02 at 20 43 11](https://user-images.githubusercontent.com/17368530/199644092-eaad16b8-e54c-4cb2-a759-02558abe5e2d.png).

**Comment by rvanasa** [comment]
Does the `.vessel` directory contain the file which is mentioned in the error message? 

Also, does this happen everywhere or just for a specific project? I'm currently looking for a way to reproduce this on my end.

**Comment by ByronBecker** [comment]
> I'm currently looking for a way to reproduce this on my end.

Sure, I find the https://github.com/ByronBecker/motoko-library-template is a decent reproducible example. Both the `src/Library.mo` and `test/Test.mo` files have this issue.

**Comment by rvanasa** [comment]
This repository works as expected for me, so I'm guessing this has something to do with the `.vessel` directory being out of sync with the package-set. 

Does this persist after deleting `.vessel` and restarting the language server?

**Comment by ByronBecker** [comment]
Thanks! It looks like doing that resolved the issue is question.

I now have a different issue, where (in the same project), it seems like in the test directory it's not able to pick up on matchers as an import.


![Screen Shot 2022-11-03 at 11 31 00](https://user-images.githubusercontent.com/17368530/199805846-e11e39e5-e8bb-481e-8f66-ad7a9f3b938b.png)

However, in a different project that I'm working on based off of the same template and vessel imports, this project doesn't appear. Is there some sort of caching going on, or a command I can run to force the program to re-check imported packages with the language server?

**Comment by ByronBecker** [comment]
@rvanasa, since the original issue seems to be fixed I'll close this issue for upkeep - but if you want to discuss the follow-up issue in the comment directly above ☝️  we can do so here, or via the forums (whatever you prefer)

**Comment by rvanasa** [comment]
Sounds good. I'll open a new issue to address nested Vessel projects, since this seems to be the most frequent blocker in  the extension right now.

**Comment by rvanasa** [comment]
Reopened #66, which appears to be the same issue.
