### ISSUE TITLE
nested projects vessel dependencies not recognized

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/vscode-motoko#95]
when working with gitsubmodules and nested dfx projects, inner vessel dependencies are not recognized by the LS.
see [this repo](https://github.com/flowerpowerdao/fpd) for example

**Comment by rvanasa** [comment]
This is a long-standing issue (more details in #66) that I will do my best to fix for you as soon as possible. 

As a short-term workaround, you could try opening the directory containing the `vessel.dhall` file in a new VS Code window.

**Comment by rvanasa** [comment]
This should be fixed in `v0.5.9`. Let me know if you run into any issues, since there might still be some corner cases due to the complexity of this change.
